"""Константы проекта, используемые в моделях, сериализаторах и view."""

import string

EMAIL_MAX_LENGTH = 256
USERNAME_MAX_LENGTH = 100
FIRST_NAME_MAX_LENGTH = 256
LAST_NAME_MAX_LENGTH = 256
USERNAME_REGEX = r'^[\w.@+-]+$'

INGREDIENT_NAME_MAX_LENGTH = 128
MEASUREMENT_UNIT_MAX_LENGTH = 64

TAG_NAME_MAX_LENGTH = 32
TAG_SLUG_MAX_LENGTH = 32

RECIPE_NAME_MAX_LENGTH = 256
SHORT_CODE_MAX_LENGTH = 8
SHORT_CODE_LENGTH = 3
SHORT_CODE_ALPHABET = string.ascii_letters + string.digits
MIN_COOKING_TIME = 1

MIN_INGREDIENT_AMOUNT = 1

PAGE_SIZE = 6
